# Generated by Django 3.1.2 on 2020-11-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='ericpro',
        ),
    ]
