# Generated by Django 3.1.2 on 2020-11-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201115_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ericpro',
            name='cata',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
