# Generated by Django 3.1.2 on 2020-11-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ericorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ericorder',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ericorder',
            name='shopprice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
