# Generated by Django 3.1.2 on 2020-11-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201126_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ericorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
