# Generated by Django 3.1.2 on 2020-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201130_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ericpro',
            name='image1',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
