# Generated by Django 3.1.2 on 2020-12-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201202_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ericpro',
            name='image1',
            field=models.ImageField(upload_to='logo/ppp1.png'),
        ),
    ]
