# Generated by Django 3.1.2 on 2020-12-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20201205_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ericpro',
            name='image1',
        ),
    ]
