# Generated by Django 3.1.2 on 2020-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_ericpro_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ericpro',
            name='image1',
            field=models.ImageField(default='eee', upload_to='logo'),
            preserve_default=False,
        ),
    ]
