# Generated by Django 3.1.2 on 2020-12-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ericpro_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ericpro',
            name='description',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ericpro',
            name='image2',
            field=models.ImageField(default='bb', upload_to='pphoto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ericpro',
            name='image3',
            field=models.ImageField(default='c', upload_to='pphoto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ericpro',
            name='image1',
            field=models.ImageField(upload_to='pphoto'),
        ),
    ]
