# Generated by Django 3.1.2 on 2020-12-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201205_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ericpro',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
