# Generated by Django 3.1.2 on 2021-05-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210417_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='ericorder',
            name='tradeinfo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ericorder',
            name='tradesha256',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
