# Generated by Django 3.1.2 on 2021-05-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210523_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='ericuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='ericuser',
            name='usermail',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
