# Generated by Django 3.1.2 on 2021-06-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20210530_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='ericuser',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ericuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
